services:
  - type: web
    name: api.holiday.ph
    runtime: python
    repo: https://github.com/irohmanzano/OfficialGazettePH-HolidayAPI
    plan: free
    branch: main
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
